### ISSUE TITLE
Prism with selection flag and RMF issue

### ISSUE THREAD

**Issue by shruthivis** [isblab/prism#36]
1. Selection flag needs selection file as input which is never provided. Need input argument for this. 
2. In RMF option, need to be able to look at all frames of an RMF. Similarly perhaps in PDB and mmCIF options: are we looking at all models in the file.

**Comment by shruthivis** [comment]
2. not addressed. 
3. https://github.com/isblab/prism/blob/510d2c68930de181f63ad38d72dec513ba0ff436/src/rmf_parser.py#LL104C156-L104C156 : all_frames is not set 
Also commented lines can be removed. 
4. Add in argument parser for main.py in the help string that this can be a folder containing 1 RMF with all models or multiple RMFs.

**Comment by Kenobi98** [comment]
> 2. not addressed.
> 3. https://github.com/isblab/prism/blob/510d2c68930de181f63ad38d72dec513ba0ff436/src/rmf_parser.py#LL104C156-L104C156 : all_frames is not set
>    Also commented lines can be removed.
> 4. Add in argument parser for main.py in the help string that this can be a folder containing 1 RMF with all models or multiple RMFs.

4. _get_number_of_beads() is a deprecated function, not being used anywhere.

**Comment by shruthivis** [comment]
3. line 102  inf = RMF.open_rmf_file_read_only(files_path[0]) instead of this should be (path) in the argument. Not necessary that the number of frames in each RMF will match that of the first one. 
4. Please remove this comment in arg parse as it looks weird to specify just for RMF.

**Comment by shruthivis** [comment]
5. To readme. Example. PrISM on binary DCD files (DCD input).  
DCD files from IMP usually have models deposited at resolution = 1. So run PrISM with resolution =1 for these types of models.

**Comment by shruthivis** [comment]
4 and 5 not addressed?
